### ISSUE TITLE
[meta] List stale components configurations per host to split a reconfigure

### ISSUE THREAD

**Issue by PaulFarault** [TOSIT-IO/tdp-lib#348]
[We want to be able to split the generation of the deployment plan into several times (#308).

To achieve this, we need to track stales configurations. Hence, to persist the state of each component/host that have been edited in the database. The following tables are required:

- **stale_component**: to track the states of the stale component in the context of a reconfigure.

  ```txt
  service_name | component_name | to_reconfigure | to_restart | (to_check, to add later) | (node, to add later)
  ```

- **component_versions_log**: the actual service_component_log table, to link the configurations version to a deployment.

  ```txt
  deployment_id | service_name | component_name | config_version | (node, to add later)
  ```

Adding a `stale` command is required to interact with the new table, with the following sub-commands:

- `tdp stale`, print a list of operations to reconfigure the components from the stale_component table.
- `tdp stale --generate`, to populate the stale_component table.
- `tdp stale add`, to add a service or component to the stale list.
- `tdp stale remove` to remove a service or component from the stale list (for advanced users).

Ideally, the stale_component table should be populated at each configuration edition. This requires a specific command to edit the configurations. However, the `tdp stale --generate` command could be used in the event where a config is edited by hand.

Then, the `tdp plan reconfigure` command should be re-implemented so that it can use the stale_component table.

---

#### Status

- [x] Refactor the service_component_log to the component_version_log table (#353)
- [X] Refactor the `ServiceVariables.component_modified` (#362 )
- [x] Create the `tdp stale` command with the `--generate` option and the stale_component table (#378)
- [ ] Allow to override stale status (#461)
- [x] Rewrite the `tdp plan reconfigure` command to use the stale_component table (#379)

**Comment by sergkudinov** [comment]
Suggesting to also add the `tdp stale list` command to list services and components.

**Comment by PaulFarault** [comment]
Edit: the `stale` command has been migrated to `status` in #448
